# Generated by Django 5.2.14 on 2026-05-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_payment_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isMember',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
