# Generated by Django 5.2.14 on 2026-06-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_ismember_user_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
