# Generated by Django 4.2.7 on 2026-06-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ticket_message_ticket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthlyLimit',
            field=models.IntegerField(default=1500),
        ),
    ]
