# Generated by Django 4.2.7 on 2026-06-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emails_sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='emails_sent_month',
            field=models.CharField(default='', max_length=7),
        ),
    ]
