# Generated by Django 4.2.7 on 2026-06-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_emails_sent_count_user_emails_sent_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leads_generated_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='leads_generated_month',
            field=models.CharField(default='', max_length=7),
        ),
    ]
